[package]
name = "algorithm"
version = "0.1.0"
authors = ["ipersona <freedom2028@gmail.com>"]

[dependencies]
ndarray = "0.11.0"
quickersort = "3.0.1"
rand = "0.4.2"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.14"
